### ISSUE TITLE
Xcode Autocomplete

### ISSUE THREAD

**Issue by felix-dumit** [hironytic/BFTaskPromise#1]
Hey,

I really like the idea of this project and want to use it in my code as I feel it will make my code more readable. However Xcode does not autocomplete the block parameter of the `then` function and take a significant amount of more time typing in the block versus autocomplete.

Do you know of any way to make Xcode autocomplete that?

Thanks!

**Comment by hironytic** [comment]
I'm afraid I have no idea about that.:disappointed:
Please let me know if you find a nice solution.

**Comment by felix-dumit** [comment]
Ok thanks.

Also I made a repo with some useful `BFTask` extras: [BFTask-Extras](https://github.com/felix-dumit/BFTask-Extras).
If I manage to fix this autocomplete thing I would like to integrate your syntax into it, maybe add yours as a subspec and convert my methods to this syntax. Is that cool?

Update: I found a solution by creating snippets for each of the methods. Here is an example for one of them: 
[BFTask-thenOnMain](https://github.com/felix-dumit/Xcode-Snippets/blob/master/bftask-thenonmain.m)

**Comment by hironytic** [comment]
Yes, it is cool. Feel free to integrate.
I took a look at your BFTask-Extras.  They are really nice things.

BTW, how can I use your Xcode snippets?

**Comment by felix-dumit** [comment]
You can copy paste them into Xcode then drag to the snippets section or use this [Xcode Plugin](https://github.com/acoomans/ACCodeSnippetRepositoryPlugin) which will sync snippets with a github repo.
I those snippets aren't  updated yet as I've decided to change some stuff with your implementation. 
For example since the `then` block is only run on success, I added a block with an id as parameter so you can automatically unpack the result, which will look a lot like the javascript version. Example:

``` objc
BFTask* task = [BFTask taskWithResult:@"result"];
task.then(^id(NSString* result){
     // result == @"result"
    return nil;
});
```

I did the same for the catch error case, with only an error as parameter (if it is an exception I convert it to a error).

This update is on my repo, I haven't updated the documentation yet but you can look at the source file `BFTask+PromiseLike`.

**Comment by hironytic** [comment]
Thanks for snippets. I now can use it.:smiley:
This would be a solution. I'll close this issue.

For your changes about parameter, it looks good to me at a glance but let me think about it.
Mey be it breaks backwards-compatibility.
I'd like to apply your changes to my repo if I think it's better in the end. Thanks!

**Comment by felix-dumit** [comment]
I was trying to use this in a swift project I was doing, but I could not figure how how to use this `.then()` syntax with swift. Do you have any ideas?

**Comment by hironytic** [comment]
How about this?

``` swift
fooAsync().then()! { value in
    // do something with value
    return nil
}
```

But I think `then` should not be used with Swift, because normal methods can be chained in dot notation.
For example, you can use `thenWithExecutor:withBlock:` method like this:

``` swift
doSomethingAsync().thenWithExecutor(BFExecutor.defaultExecutor()) { str in
    return "abc"
}.thenWithExecutor(BFExecutor.defaultExecutor()) { str in
    println(str)
    return nil
}
```

...I'd like to use native libraries written in Swift like [PromiseKit](https://github.com/mxcl/PromiseKit) though. :sweat:
