### ISSUE TITLE
id, instead of BFTask, as a parameter of then-block

### ISSUE THREAD

**Issue by hironytic** [hironytic/BFTaskPromise#2]
See #1, @felix-dumit's comment:

> For example since the `then` block is only run on success, I added a block with an id as parameter so you can automatically unpack the result, which will look a lot like the javascript version.

And the same for `catch`.
It may break backwards-compatibility though.

**Comment by felix-dumit** [comment]
Yes so it would break backwards compatibility which is why I have it separately on my repo for now, If you want I can make a pull request.

Something I also changed because I needed in the project I'm working on is in the finally block allowing it to return another task, not discarding what is returned by the block and using the previous result.

I have some code that I need to run regardless of success or error and then I need to continue that with another task.

**Comment by hironytic** [comment]
In my opinion, you would need something like `then(onFulfilled, onRejected)` in Javascript Promise rather than `finally`. I think `finally` should be used for cleaning up. So it should not change the result value (unless an error occurs in itself; I've fixed this, see #3).

For example:

``` objc
- (BFTask *)executeAsync {
    return [self setUpAsync].then(^id(BFTask *task) {
        return [self readDataAsync];
    }).finally(^BFTask *() {
        return [self tearDownAsync];
    });
}

- (void)retrieveResult
{
    [self executeAsync].then(^id(BFTask *task) {
        NSLog(@"the result value is %@", task.result);
        return nil;
    });
}
```

The last `NSLog` should be executed after `tearDownAsync` but I want the result value of `readDataAsync` as the `task.result`.

**Comment by hironytic** [comment]
@felix-dumit It would help me if you could make a pull request about your changes.

**Comment by felix-dumit** [comment]
Ok I guess it makes change it that scenario for finally. I think we really need another method for what I was intending. 

I will make a pull request with my changes when I get a change this week. :+1:

**Comment by hironytic** [comment]
@felix-dumit I finally decided to accept your suggestion for `then` and `catch`. :+1: 
I'm going to merge your work.

**Comment by hironytic** [comment]
Merged. :smiley: 
The version will be bumped to 2.0.0 on next release.
